name: ${project.name}
version: ${project.version}
description: ${project.description}
main: ${project.groupId}.tf2.TF2
authors: [chaseoes, psycowithespn]
softdepend: [WorldEdit, Multiverse-Core, ForceRespawn]
commands:
  ${project.name}:
    description: The central command for ${project.name}.
    usage: /${project.name} <command> [args]
